#!/usr/bin/env python3
import argparse
import json
import os
import subprocess
import re

# --- PATHS ---
WORK_DIR = os.path.expanduser("/scratch/naouasal")
CHIPYARD_DIR = os.path.join(WORK_DIR, "chipyard")
SIM_DIR = os.path.join(CHIPYARD_DIR, "sims/verilator")
JSON_FILE = os.path.join(WORK_DIR, "boom_configs.json")

# Scala files we will modify
MIXINS_FILE = os.path.join(CHIPYARD_DIR, "generators/boom/src/main/scala/common/config-mixins.scala")
CONFIGS_FILE = os.path.join(CHIPYARD_DIR, "generators/chipyard/src/main/scala/config/BoomConfigs.scala")

# --- 1. GENERATE JSON ---
def generate_json():
    configs = {}
    config_id = 0
    
    # Define our search space
    fetch_widths = [4, 8] # Power of 2
    decode_widths = [2, 3, 4]
    rob_sizes = [64, 96, 128]
    
    for fw in fetch_widths:
        for dw in decode_widths:
            # Constraint 1: Decode cannot be wider than Fetch
            if dw > fw:
                continue
                
            for rob in rob_sizes:
                # Constraint 2: ROB must be perfectly divisible by decodeWidth
                if rob % dw != 0:
                    continue
                
                # Constraint 3: Register files must be at least 32 + decodeWidth
                min_regs = 32 + dw
                int_regs = max(80, min_regs + 20) # Add some buffer
                fp_regs = max(64, min_regs + 10)
                
                name = f"DSEBoomConfig{config_id}"
                configs[name] = {
                    "fetchWidth": fw,
                    "fetchBytes": fw * 2, # Constraint 4: RISC-V 16-bit compressed instruction math
                    "decodeWidth": dw,
                    "numFetchBufferEntries": fw * 4,
                    "numRobEntries": rob,
                    "numIntPhysRegisters": int_regs,
                    "numFpPhysRegisters": fp_regs,
                    # Keeping issue queues stable for this initial sweep to isolate front-end/ROB performance
                    "issueMem": 1,
                    "issueInt": 2,
                    "issueFp": 1
                }
                config_id += 1

    with open(JSON_FILE, 'w') as f:
        json.dump(configs, f, indent=4)
    print(f"Generated {len(configs)} valid configurations and saved to {JSON_FILE}")


# --- 2. BUILD SCALA & VERILATOR ---
def build_config(config_name):
    if not os.path.exists(JSON_FILE):
        print(f"Error: {JSON_FILE} not found. Run 'generate' first.")
        return

    with open(JSON_FILE, 'r') as f:
        configs = json.load(f)

    if config_name not in configs:
        print(f"Error: Configuration '{config_name}' not found in JSON.")
        return

    params = configs[config_name]
    print(f"Injecting parameters for {config_name}: {params}")

    mixin_name = f"With{config_name}Tweaks"

    # 1. Generate the Mixin Scala Code (without package declaration since we're appending)
    mixin_code = f"""
// --- AUTO-GENERATED BY DSE SCRIPT FOR {config_name} ---
class {mixin_name} extends Config((site, here, up) => {{
  case TilesLocated(InSubsystem) => up(TilesLocated(InSubsystem), site) map {{
    case attach: BoomTileAttachParams => 
      attach.copy(
        tileParams = attach.tileParams.copy(
          core = attach.tileParams.core.copy(
            fetchWidth = {params['fetchWidth']},
            decodeWidth = {params['decodeWidth']},
            numFetchBufferEntries = {params['numFetchBufferEntries']},
            numRobEntries = {params['numRobEntries']},
            numIntPhysRegisters = {params['numIntPhysRegisters']},
            numFpPhysRegisters = {params['numFpPhysRegisters']},
            issueParams = Seq(
               IssueParams(issueWidth={params['issueMem']}, numEntries=16, iqType=IQT_MEM.litValue, dispatchWidth={params['decodeWidth']}),
               IssueParams(issueWidth={params['issueInt']}, numEntries=20, iqType=IQT_INT.litValue, dispatchWidth={params['decodeWidth']}),
               IssueParams(issueWidth={params['issueFp']}, numEntries=16, iqType=IQT_FP.litValue , dispatchWidth={params['decodeWidth']})
            )
          ),
          icache = Some(attach.tileParams.icache.get.copy(fetchBytes = {params['fetchBytes']})),
          dcache = Some(attach.tileParams.dcache.get.copy(nMSHRs = 4))
        )
      )
    case other => other
  }}
}})
"""
    # Append to the mixin file (avoid duplicates)
    with open(MIXINS_FILE, 'r') as f:
        mixins_content = f.read()
    
    if f'class {mixin_name} extends Config' in mixins_content:
        import re
        pattern = rf'// --- AUTO-GENERATED BY DSE SCRIPT FOR {config_name} ---\s*\nclass {mixin_name} extends Config\([\s\S]*?\n\)\n'
        mixins_content = re.sub(pattern, '', mixins_content, flags=re.DOTALL)
    
    # Now append the new mixin code
    with open(MIXINS_FILE, 'w') as f:
        f.write(mixins_content.rstrip() + '\n' + mixin_code)

    # 2. Generate the Top-level Config Code
    config_code = f"""
// --- AUTO-GENERATED BY DSE SCRIPT ---
class {config_name} extends Config(
  new boom.common.{mixin_name} ++ 
  new boom.common.WithNMediumBooms(1) ++ 
  new chipyard.config.AbstractConfig
)
"""
    # Append to the config file (avoid duplicates)
    with open(CONFIGS_FILE, 'r') as f:
        configs_content = f.read()
    
    if f'class {config_name} extends Config' in configs_content:
        # Remove old config if it exists
        import re
        pattern = rf'\n// --- AUTO-GENERATED BY DSE SCRIPT ---\nclass {config_name} extends Config\(.*?\n\)\n'
        configs_content = re.sub(pattern, '', configs_content, flags=re.DOTALL)
    
    # Now append the new config
    with open(CONFIGS_FILE, 'w') as f:
        f.write(configs_content.rstrip() + '\n' + config_code)

    print(f"Scala files updated. Starting Verilator build for {config_name}...")
    
    # 3. Call Make
    cmd = f"make CONFIG={config_name}"
    try:
        subprocess.run(cmd, shell=True, cwd=SIM_DIR, check=True)
        print(f"\n[SUCCESS] Build complete for {config_name}!")
        return True
    except subprocess.CalledProcessError as e:
        print(f"\n[ERROR] Build failed for {config_name}: {e}")
        return False


# --- 3. RUN BENCHMARK ---
def run_benchmark(config_name, binary_path):
    print(f"Running benchmark {binary_path} on {config_name}...")
    
    # The fast execution command (no +verbose)
    cmd = [
        f"./simulator-chipyard.harness-{config_name}",
        "+permissive",
        "+dramsim",
        "+dramsim_ini_dir=../../generators/testchipip/src/main/resources/dramsim2_ini",
        "+max-cycles=10000000",
        "+permissive-off",
        binary_path
    ]
    
    result = subprocess.run(cmd, cwd=SIM_DIR, capture_output=True, text=True)
    
    # Extract Data using Regex
    output = result.stdout
    cycles_match = re.search(r"Total Cycles:\s+(\d+)", output)
    inst_match = re.search(r"Total Instructions:\s+(\d+)", output)
    ipc_match = re.search(r"Calculated IPC:\s+([0-9.]+)", output)
    
    if cycles_match and ipc_match:
        print(f"\n--- RESULTS FOR {config_name} ---")
        print(f"Cycles: {cycles_match.group(1)}")
        print(f"Instructions: {inst_match.group(1)}")
        print(f"IPC: {ipc_match.group(1)}")
        print("-----------------------------------")
        return (cycles_match.group(1), inst_match.group(1), ipc_match.group(1))
    else:
        print("\nFailed to parse benchmark output. Raw output:")
        print(output)
        return None


# --- 4. BATCH PROCESS ---
def run_batch(binary_path, out_file):
    if not os.path.exists(JSON_FILE):
        print(f"Error: {JSON_FILE} not found. Run 'generate' first.")
        return

    with open(JSON_FILE, 'r') as f:
        configs = json.load(f)

    print(f"Starting batch run of {len(configs)} configs...")
    with open(out_file, 'w') as f:
        f.write("Starting Automated DSE Benchmarks...\n")
        f.write("=====================================\n")

    for config_name in configs.keys():
        print(f"\nProcessing Config: {config_name}")
        with open(out_file, 'a') as f:
            f.write(f"\nProcessing Config: {config_name}\n")
        
        success = build_config(config_name)
        if not success:
            with open(out_file, 'a') as f:
                f.write(f"--> [ERROR] Build failed for {config_name}. Skipping.\n")
            continue
            
        res = run_benchmark(config_name, binary_path)
        with open(out_file, 'a') as f:
            if res:
                f.write(f"--- RESULTS FOR {config_name} ---\n")
                f.write(f"Cycles: {res[0]}\n")
                f.write(f"Instructions: {res[1]}\n")
                f.write(f"IPC: {res[2]}\n")
            else:
                f.write(f"--> [ERROR] Failed to run or parse benchmark for {config_name}.\n")
                
    print(f"\nBatch complete. Results saved to {out_file}")


# --- CLI ARGUMENT PARSER ---
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="BOOM Design Space Exploration Manager")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # Command: generate
    parser_gen = subparsers.add_parser("generate", help="Generate boom_configs.json")

    # Command: build
    parser_build = subparsers.add_parser("build", help="Inject Scala and compile Verilator simulator")
    parser_build.add_argument("config_name", help="Name of the config from the JSON file (e.g. DSEBoomConfig_0)")

    # Command: run
    parser_run = subparsers.add_parser("run", help="Run a compiled binary on a specific simulator")
    parser_run.add_argument("config_name", help="Name of the config to run on")
    parser_run.add_argument("binary", help="Path to the .riscv binary")

    # Command: batch
    parser_batch = subparsers.add_parser("batch", help="Batch iteration: build configs, run benchmark, and save results")
    parser_batch.add_argument("binary", help="Path to the .riscv binary (e.g., /scratch/naouasal/chipyard/tests/fft_dummy.riscv)")
    parser_batch.add_argument("--output", "-o", default="benchmark_results.log", help="Output file to log results")

    args = parser.parse_args()

    if args.command == "generate":
        generate_json()
    elif args.command == "build":
        build_config(args.config_name)
    elif args.command == "run":
        # Resolve to absolute path before passing
        abs_binary = os.path.abspath(args.binary)
        run_benchmark(args.config_name, abs_binary)
    elif args.command == "batch":
        abs_binary = os.path.abspath(args.binary)
        abs_output = os.path.abspath(args.output)
        run_batch(abs_binary, abs_output)
