#!/usr/bin/env python3
import argparse
import json
import os
import subprocess

# --- PATHS ---
WORK_DIR = os.path.expanduser("/scratch/naouasal")
CHIPYARD_DIR = os.path.join(WORK_DIR, "chipyard")
FPGA_DIR = os.path.join(CHIPYARD_DIR, "fpga")
SIM_DIR = os.path.join(CHIPYARD_DIR, "sims/verilator")
JSON_FILE = os.path.join(WORK_DIR, "rocket_configs.json")

# Scala files we will modify
HETERO_CONFIGS_FILE = os.path.join(CHIPYARD_DIR, "generators/chipyard/src/main/scala/config/HeteroConfigs.scala")
FPGA_CONFIGS_FILE = os.path.join(FPGA_DIR, "src/main/scala/vc707/Configs.scala")

# --- 1. GENERATE JSON ---
def generate_json():
    configs = {}
    config_id = 0
    
    # Define our search space for Rocket Cmp
    big_cores = [1, 2] 
    small_cores = [0, 1]
    
    for bc in big_cores:
        for sc in small_cores:
            if bc == 0 and sc == 0:
                continue
                
            name = f"DSERocketConfig{config_id}"
            fpga_name = f"{name}VC707"
            configs[name] = {
                "bigCores": bc,
                "smallCores": sc,
                "fpgaConfigName": fpga_name
            }
            config_id += 1

    with open(JSON_FILE, 'w') as f:
        json.dump(configs, f, indent=4)
    print(f"Generated {len(configs)} Rocket configurations and saved to {JSON_FILE}")


# --- 2. BUILD SCALA & VERILATOR ---
def build_config(config_name):
    if not os.path.exists(JSON_FILE):
        print(f"Error: {JSON_FILE} not found. Run 'generate' first.")
        return

    with open(JSON_FILE, 'r') as f:
        configs = json.load(f)

    if config_name not in configs:
        print(f"Error: Configuration '{config_name}' not found in JSON.")
        return

    params = configs[config_name]
    fpga_config_name = params['fpgaConfigName']
    print(f"Injecting parameters for {config_name}: {params}")

    # 1. Base Config for Chipyard
    hetero_code = f"""
// --- AUTO-GENERATED BY DSE SCRIPT FOR {config_name} ---
class {config_name} extends Config(
  new freechips.rocketchip.subsystem.WithNBigCores({params['bigCores']}) ++
  new freechips.rocketchip.subsystem.WithNSmallCores({params['smallCores']}) ++
  new chipyard.config.WithSystemBusWidth(128) ++
  new chipyard.config.AbstractConfig)
"""
    
    with open(HETERO_CONFIGS_FILE, 'a') as f:
        f.write(hetero_code)

    # 2. Wrapping Config for the FPGA (VC707)
    fpga_code = f"""
// --- AUTO-GENERATED BY DSE SCRIPT FOR {config_name} ---
class {fpga_config_name} extends Config(
  new WithFPGAFrequency(50) ++
  new WithVC707Tweaks ++
  new chipyard.{config_name}
)
"""

    with open(FPGA_CONFIGS_FILE, 'a') as f:
        f.write(fpga_code)

    print(f"Scala files updated. Starting FPGA Bitstream build for {fpga_config_name}...")
    
    # 3. Call Make to build the FPGA bitstream
    cmd = f"make SUB_PROJECT=vc707 CONFIG={fpga_config_name} bitstream"
    try:
        subprocess.run(cmd, shell=True, cwd=FPGA_DIR, check=True)
        print(f"\n[SUCCESS] Bitstream generation initiated/completed for {fpga_config_name}!")
        return True
    except subprocess.CalledProcessError as e:
        print(f"\n[ERROR] Build failed for {fpga_config_name}: {e}")
        return False

def build_sim(config_name):
    if not os.path.exists(JSON_FILE):
        print(f"Error: {JSON_FILE} not found. Run 'generate' first.")
        return

    print(f"Starting Verilator simulation build for base config: {config_name}...")
    cmd = f"make CONFIG={config_name}"
    try:
        subprocess.run(cmd, shell=True, cwd=SIM_DIR, check=True)
        print(f"\n[SUCCESS] Verilator simulator built for {config_name}!")
        return True
    except subprocess.CalledProcessError as e:
        print(f"\n[ERROR] Verilator build failed for {config_name}: {e}")
        return False

def run_sim(config_name, binary_path):
    sim_binary = os.path.join(SIM_DIR, f"simulator-chipyard.harness-{config_name}")
    if not os.path.exists(sim_binary):
        print(f"Error: Simulator binary not found: {sim_binary}. Run 'build-sim {config_name}' first.")
        return

    if not os.path.exists(binary_path):
        print(f"Error: Target binary not found: {binary_path}.")
        return

    print(f"Running simulation for {config_name} with binary {binary_path}...")
    cmd = f"{sim_binary} {binary_path}"
    try:
        subprocess.run(cmd, shell=True, cwd=SIM_DIR, check=True)
    except subprocess.CalledProcessError as e:
        print(f"\n[ERROR] Simulation run failed or threw an error: {e}")

def main():
    parser = argparse.ArgumentParser(description="Rocket Chip FPGA Design Space Exploration Script")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # generate command
    subparsers.add_parser('generate', help="Generate the JSON configuration space")

    # build command
    build_parser = subparsers.add_parser('build', help="Build an FPGA bitstream for a specific config")
    build_parser.add_argument('config_name', help="Name of the configuration to build (e.g. DSERocketConfig0)")

    # build-sim command
    build_sim_parser = subparsers.add_parser('build-sim', help="Build a Verilator simulator for a specific config")
    build_sim_parser.add_argument('config_name', help="Name of the configuration to build (e.g. DSERocketConfig0)")

    # run-sim command
    run_sim_parser = subparsers.add_parser('run-sim', help="Run the Verilator simulator for a specific config")
    run_sim_parser.add_argument('config_name', help="Name of the configuration (e.g. DSERocketConfig0)")
    run_sim_parser.add_argument('binary_path', help="Path to the RISC-V binary (e.g. ../../tests/build/fft_dummy.riscv)")

    args = parser.parse_args()

    if args.command == 'generate':
        generate_json()
    elif args.command == 'build':
        build_config(args.config_name)
    elif args.command == 'build-sim':
        build_sim(args.config_name)
    elif args.command == 'run-sim':
        run_sim(args.config_name, os.path.abspath(args.binary_path))

if __name__ == "__main__":
    main()
